jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          command: |
              python setup.py bdist_wheel
  test:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          command: |
              python setup.py bdist_wheel
              pip --user install .
              python -m pytest tests/
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
