jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          command: |
              python setup.py bdist_wheel
  test:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          command: |
              python setup.py bdist_wheel
              pip install --user  .
              python -m pytest tests/
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
