jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          command: |
              python setup.py bdist_wheel
  test:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          command: |
              python setup.py bdist_wheel
              pip install .
              pip install -r requirements-dev.txt
              rm -rf dwdweather/
              python -m pytest tests/
  python_lint:
     docker:
       - image: circleci/python:3.7.3-stretch
     steps:
       - checkout
       - run:
           command: |
               pip install black
       - run:
           name: run black
           command: black . --check
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
